- js/lib/monster.js
When using the Kazoo SDK to make API requests in Monster (e.g. via self.callApi), the dialog popup on request error only shows a message related to the error code (e.g. "Access forbidden." for 403).
This PR displays the API error message in the dialog popup as well.
> Show API error message in dialog popup from kazoo SDK.

- js/lib/jquery.kazoosdk.js
> UI-1701: typo in sdk causes the user-portal quickcall to fail

- js/lib/monster.js
Error data wasn't being proliferated through when error wasn't a 402, parsedError variable wasn't being assigned in other branches.
> Fixed issue with error messages in monster.request

- apps/common/submodules/servicePlanDetails/servicePlanDetails.js
Adds additional argument 'useOwnPlans', which is set to true for resellers. This allows a reseller to assign his own service plans instead of his parent's service plans. Affects only the "Add New Account" wizard.
See the corresponding pull request for the monster-ui-accounts repo (https://github.com/2600hz/monster-ui-accounts/pull/8)
> UI-1918 use reseller's own service plans

- apps/common/submodules/accountBrowser/accountBrowser.js
Its possible that the data stored in the DOM, and retrieved using jQuery's data() function could return a numeric value. By casting this to a string before calling toLowerCase() we prevent any exception that would break search. This is possible in cases where the data returned is of the form...
```json
{
"id": "asdfasfdsadsasdf",
"name": 1234,
"realm": "1234.something.com"
}
```
> fix(accounts): Coerce numerics to strings during search

- src/js/lib/monster.util.js
Hi,
this fix should prevent strange formatting of non US numbers, with length between 10 and 12 digits.
For example, without this, number "+3531xxxyyzz", will be turned into: "+3+1 (531) xxx-yyzz"
Thanks,
Mario
> Numbers formatting US Regex should only match US numbers

- src/apps/core/app.js
- src/js/lib/monster.js
- src/js/lib/monster.ui.js
Separate spinner and request detection logic and and the latter instead of the former to show the loading template.
> UI-2699: Fix event binding on spinner start

- src/js/lib/monster.socket.js
When two bindings are created in close succession (to the same routing key), one can overwrite the other.
> Fix race condition when binding multiple listeners to websocket

- src/apps/apploader/app.js
- src/apps/apploader/style/app.scss
- src/apps/apploader/views/appList.html
- src/apps/core/app.js
- src/apps/core/views/app.html
- src/js/config.js
This change would allow an alternative apploader to be used, if desired, by enabling and configuring it through settings in config.js. This alternative apploader is a drop-down menu of apps, which is faster to select from and could be a more practical option for accounts with few apps. Additionally, it is possible to choose whether or not to expose the App Store in the drop-down - if not enabled via config.js, it will be hidden from admins too.
> Add alternative apploader

- src/apps/apploader/app.js
- src/js/config.js
The appstore is exposed to admin users by default. Setting the new hideAppStore flag to true in the config file will hide the appstore from all users.
> Add flag for hiding appstore from all users

- src/js/lib/monster.js
I would like to be able to use filters with custom API request definitions. This pull request adds the capacity for filters to monster.request() and achieves this in a similar way to how it is done in self.callApi().
> Add capacity for filters to monster.request

- src/apps/common/i18n/en-US.json
- src/apps/common/submodules/portWizard/portWizard.js
- src/apps/common/submodules/portWizard/views/accountVerification.html
At least in English, it's more natural to put the street name followed by the street type. An example of this is our office, "140 Geary St" (number->name->street type). When using the UI to submit a port request, the order felt unnatural and confused me for a second, so this PR addresses that.
> UI-3200: Switch address inputs

- src/apps/common/submodules/numbers/numbers.js
- src/js/lib/monster.util.js
Numbers with `state === 'port_in'` or mobile numbers do not have the properties `features_available` nor `_read_only.features_available`. However, they both have the property `features`, so an extra check was added for this one.
> UI-3313: Avoid getNumberFeatures() failure when number is mobile or is being ported

- docs/monster-util/getNumberFeatures().md
- src/js/lib/monster.util.js
The previous check was strictly enforcing `number` to be a Kazoo phone
number, meaning that objects without the required props would throw an
error.
This behavior is not backward compatible with current usage (PBX
Connector for example) and it would take too long to refacor those use
cases on an app by app basis.
THe solution it to loosely check for the props related to number feature
and return an empty array when missing/already empty.
> OOB: Loosely check for Kazoo number feature  props

- src/apps/myaccount/submodules/balance/balance.js
Bug introduced in #230 Typo for caller/callee in balance.js
> [master] QF: UI-3219 Bug introduced in #230

- src/apps/common/submodules/portWizard/portWizard.js
Street direction properties are not allowed to be empty so we remove
them when that is the case to avoid validation errors.
This fix involved creating a method to normalize port request data to
follow API schema.
> UI-3347: Mutate portRequest to follow API schema

- gulp/helpers/helpers.js
- gulp/paths.js
- gulp/tasks/clean-move.js
- gulp/tasks/javascript.js
- gulp/tasks/require.js
- gulp/tasks/style.js
- gulp/tasks/templates.js
- gulp/tasks/watch-sources.js
- gulp/tasks/write-config.js
- gulp/tasks/write-version.js
- package-lock.json
- package.json
Format all paths in unix style (backslash) since it is supported by all
platforms.
requirejs and chokidar (used by gulp.watch) expects unix formatted paths
and silently fails when a Windows path is provided.
This change impacts the whole build system and will hopfully avoid path
related error later on.
> UI-3139: Normalize path format for all platforms

- src/js/lib/jquery.kazoosdk.js
There APIs are not longer needed for call center pro so they have been removed
> MCCP-22: Remove unused/deprecated APIs

- src/apps/myaccount/submodules/balance/balance.js
This stop-gap is not required after #342 was merged.
> UI-3377: Remove stop-gap fixing overly long dialog handling

- src/apps/common/submodules/portWizard/portWizard.js
The change is to keep the requestId after save, before status change. This will allow to know that the port request is already saved in case the status change fails, in order to update it on further attempts instead of creating a new one.
> MPOR-6: Allow to update port req on submit error

- src/apps/common/submodules/navigationWizard/navigationWizard.js
Merge the updated data into the existing `args` object, to avoid creating a full new object, that includes a new app object due to its reference via the `thisArg` property.
> MSTR-46: Merge updated data into existing args

- scripts/circleci.bash
> Use copy not symlink when building apps

- src/apps/common/submodules/portWizard/portWizard.js
This change is to not generate the default error on port state change. The errors are handled within the error callback. If the `callApi` function is left to handle the errors, it shows a dialog with the error details in an asynchronous way. This process is stopped abruptly because the wizard is rendered again, which in turn causes that the error dialog is not displayed, but the page body's scroll is disabled as if it was shown.
> MSTR-33: Prevent to disable scroll on error

- src/apps/common/submodules/portWizard/portWizard.js
This change is to not generate the default error on port state change. The errors are handled within the error callback. If the `callApi` function is left to handle the errors, it shows a dialog with the error details in an asynchronous way. This process is stopped abruptly because the wizard is rendered again, which in turn causes that the error dialog is not displayed, but the page body's scroll is disabled as if it was shown.
> [4.3] MSTR-33: Prevent to disable scroll on error

- src/apps/auth/app.js
Since the username is normalized to lowercase when a user is created in Kazoo `cb_users`, it should also be possible to authenticate with any case.
> MSTR-74: Lowercase username on login

- src/apps/common/submodules/chooseModel/chooseModel.js
Following the behaavioral update of dialogs, scrolling on the body was
disabled when a dialog is open.
Here we had to update the scrolling target when a model is selected
since the original one was body and could break the UX.
> MSTR-78: Scroll through popup rather than body when selecting models

- src/apps/common/submodules/chooseModel/chooseModel.js
Following the behaavioral update of dialogs, scrolling on the body was
disabled when a dialog is open.
Here we had to update the scrolling target when a model is selected
since the original one was body and could break the UX.
> [4.3] MSTR-78: Scroll through popup rather than body when selecting models

- scripts/validate_mkdocs.py
The following warning was thrown on CI build:
> ./scripts/validate_mkdocs.py:40: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Following the deprecation guide, this update simply specifies a `Loader=` parameter when loading the mkdoc toc.
> OOB: Handle PyYAML yaml.load(input) deprecation

- src/js/lib/monster.util.js
Hi @azefiel ,
Sorry about that in #500 , I tried updating my branch to master by issueing a pull request to myself...
Fixed that up now with a rebase and a fresh branch.
Previous description:
> Fix monster.util.friendlyTimer (corrected)

- src/js/lib/monster.util.js
> [4.3] Fix monster.util.friendlyTimer hours formatting

- src/js/lib/monster.util.js
> [4.2] Fix monster.util.friendlyTimer hours formatting

- src/js/lib/monster.util.js
> [4.1] Fix monster.util.friendlyTimer hours formatting

- src/js/lib/monster.util.js
> [4.0] Fix monster.util.friendlyTimer hours formatting

- src/apps/common/submodules/portListing/portListing.js
Right now even if the account you are currently logged in is the port authority for a given port request the UI doesn't show the `action_required` nor the `private` options when you try to create a comment on that port request, this change fixes that.
> KZOO-16: Fix port_authority property reading from port_request object

- src/apps/common/submodules/numberSelector/numberSelector.scss
Fixes link labels wrapping off their container on number entity selection.
> MSTR-119: Allow link labels to wrap inside their container

- docs/validation.md
- src/apps/core/i18n/en-US.json
- src/js/lib/monster.ui.js
This is a new custom rule for the jQuery validation plugin, to check that a form field’s value does not match one or more of other field’s values.
> MSTR-127: Add notEqualTo custom validation rule

- docs/validation.md
- src/apps/core/i18n/en-US.json
- src/js/lib/monster.ui.js
This is a new custom rule for the jQuery validation plugin, to check that a form field’s value does not match one or more of other field’s values.
> [4.3] MSTR-127: Add notEqualTo custom validation rule

- src/apps/myaccount/app.js
Previously, the onOpen callback was triggered as soon as the
`myaccount-open` class was added to myaccount's container.
Since a transition animating the height of the container was tied to
`myaccount-open` class, it means the container only reached its full
size once the transition ended.
That behavior became problematic when the onOpen callback created a
dialog, as that dialog's container would be set to myaccount's
container. Because the onOpen callback was triggered near the same time
than when the transition started, the dialog would be positioned based
on myaccount's container current height, which would be close to 0.
Now the onOpen callback it triggered once the transition ends and
myaccount's container is fully visible.
> MSTR-108: Trigger myaccount onOpen callback when container transition ended

- src/apps/myaccount/app.js
Previously, the onOpen callback was triggered as soon as the
`myaccount-open` class was added to myaccount's container.
Since a transition animating the height of the container was tied to
`myaccount-open` class, it means the container only reached its full
size once the transition ended.
That behavior became problematic when the onOpen callback created a
dialog, as that dialog's container would be set to myaccount's
container. Because the onOpen callback was triggered near the same time
than when the transition started, the dialog would be positioned based
on myaccount's container current height, which would be close to 0.
Now the onOpen callback it triggered once the transition ends and
myaccount's container is fully visible.
> [4.3] MSTR-108: Trigger myaccount onOpen callback when container transition ended

- docs/mkdocs/mkdocs.yml
- docs/monster-util/getCapability().md
- src/apps/auth/app.js
- src/js/lib/monster.util.js
The goal of this PR is to abstract capability information resolving by exposing a utility method giving easy access to such data (made available by https://github.com/2600hz/kazoo/pull/6342)
Developers are expected to access capability information like follows:
```js
monster.util.getCapability('voicemail.transcription');
// -> { isEnabled: true, defaultValue: false }
```
For more information, check out the documentation entry about this helper.
> Create utility to retrieve capability information

- src/apps/common/submodules/chooseModel/chooseModel.js
For Polycom Models, Prefix VVX in front of all VVX model names in Monster UI
The family information is already available on the payload, it just need to be added to the string displayed to avoid confusions.
> [4.3] MPRO-7: For Polycom Models, Prefix VVX in front of all VVX model names in Monster UI

- src/apps/common/submodules/conferenceViewer/conferenceViewer.js
[conference binding changed for 5.x ](https://github.com/2600hz/kazoo-blackhole/commit/565b8a63d0b6e4bef05cffd0069be7cfa0c63533)
the format is now conference.event.`Event`.`ConferenceId`.`InstanceId`
this makes it easier to subscribe to conference.event.`conference-create`.\*.* when a `superduper` or `admin` wants to track conference creation or other relevant event
> Update conference binding format

- src/apps/common/app.js
- src/apps/common/i18n/en-US.json
- src/apps/common/style/app.scss
- src/apps/common/submodules/csvUploader/_csvUploader.scss
- src/apps/common/submodules/csvUploader/csvUploader.js
- src/apps/common/submodules/csvUploader/views/layout.html
> MSTR-182: Implement csvUploader common control

- src/js/lib/jquery.kazoosdk.js
Since 5.x, kazoo checks for and enforces `X-Auth-Token` header on authentication requests, making them fail when the token provided expired/is invalid.
This new behavior breaks down our current authentication mechanism, which by default, includes the current auth token on authentication requests.
To fix this, we set the `removeHeaders` prop on authentication requests to remove the `X-Auth-Token` header and make this behavior unoverridable as this behavior is tied to kazoo's implementation.
> MSTR-184: Unset auth token header on authentication requests

- src/apps/myaccount/app.js
- src/apps/myaccount/views/app.html
The goal of this PR is to render Control Center's Transactions tab currency icon based on the currency code set in [monster ui's config](https://github.com/2600hz/monster-ui/blob/master/docs/configuration.md#settings).
Font Awesome supports 8 currency code symbols while the fallback icon used is [`fa-money`](https://fontawesome.com/v4.7.0/icon/money).
Example with `currencyCode: 'GBP'`:
Example with `currencyCode: 'AUS'` (Australian Dollar, not supported by Font Awesome):
> MSTR-195: Render currency symbol based on currency code

- src/apps/apploader/app.js
- src/apps/appstore/app.js
- src/apps/auth/app.js
- src/apps/common/submodules/appSelector/appSelector.js
- src/apps/common/submodules/servicePlanDetails/servicePlanDetails.js
- src/apps/common/submodules/servicePlanItemEditor/servicePlanItemEditor.js
- src/apps/core/app.js
- src/js/lib/monster.apps.js
- src/js/lib/monster.routing.js
- src/js/lib/monster.ui.js
- src/js/lib/monster.util.js
The goal of this PR is to abstract away app store data management operations so that app metadata access is normalized. The purpose of this change is to allow for app metadata branding on top of internationalization resolution.
Returns metadata for an appstore app formatted by resolving its icon path and i18n entry. It is this formatting logic that will be augmented later to resolve i18n based on branding configuration.
App metadata is retrieved from the current appstore, which corresponds to the current account. To perform the same operation for a different list of apps, we can use `monster.util#getAppMetadata` by providing it a custom list.
Returns formatted apps metadata filtered for a specific scope (`all|account|user`). Similarly to `monster.util#getAppStoreMetadata`, the apps …
> MSTR-197: Abstract appstore metadata management into methods

- src/apps/common/submodules/navigationWizard/navigationWizard.js
Use the `disabled` property instead of a class to disable the navigation wizard's done button. This in turn allows the done button to be re-enabled when the step is rendered again, which solves the issue of it remaining disabled even after changing the account name.
> MACT-91: Use disabled prop for wizard done button

- src/apps/common/submodules/navigationWizard/navigationWizard.js
Use the `disabled` property instead of a class to disable the navigation wizard's done button. This in turn allows the done button to be re-enabled when the step is rendered again, which solves the issue of it remaining disabled even after changing the account name.
**NOTE:** This change differs a bit from [`MACT-91`](https://github.com/2600hz/monster-ui/pull/861) because the `4.3` branch does not include the changes for the Port Request Wizard in MSTR-76.
> [4.3] MACT-91: Use disabled prop for wizard done button

- src/apps/common/submodules/navigationWizard/navigationWizard.js
Use the `disabled` property instead of a class to disable the navigation wizard's done button. This in turn allows the done button to be re-enabled when the step is rendered again, which solves the issue of it remaining disabled even after changing the account name.
**NOTE:** This change differs a bit from [`MACT-91`](https://github.com/2600hz/monster-ui/pull/861) because the changes for the Port Request Wizard in MSTR-76 were [reverted](https://github.com/2600hz/monster-ui/commit/d892e0bbd1edb51b66675596cb3337c46cb768c3) in the `5.0` branch.
> [5.0] MACT-91: Use disabled prop for wizard done button

- src/js/lib/monster.util.js
Supports https://github.com/2600hz/monster-ui-languages/pull/12
> MLAN-9: Expose supported locales in app metadata

- docs/monster-ui/mask().md
- src/js/lib/monster.ui.js
ipv4 pattern is now a part of the presets
Accepts other patterns if the specified type is not a preset, uses options the same as jquery mask
> MPRO-29: Extending monster ui mask for ipv4 and to accept other custom patterns

- docs/mkdocs/mkdocs.yml
- docs/monster-util/parseQueryString().md
- src/js/lib/monster.routing.js
- src/js/lib/monster.util.js
This change allows to redirect to a registered app, if the first 2 parts of the hash route match a valid app, on load/re-load. For example:
- `apps/callcenter/queues/abc123/members` redirects to `apps/callcenter`
- `apps/cluster/tasks` redirects to `apps/cluster`
This enables Monster UI to load, reload or redirect to apps that use their own sub-routing system.
Normal routes (app/{appName}) and invalid routes should work as usual.
> MSTR-228: Allow app custom routing

- docs/mkdocs/mkdocs.yml
- docs/monster-util/parseQueryString().md
- src/js/lib/monster.routing.js
- src/js/lib/monster.util.js
This change allows to redirect to a registered app, if the first 2 parts of the hash route match a valid app, on load/re-load. For example:
- `apps/callcenter/queues/abc123/members` redirects to `apps/callcenter`
- `apps/cluster/tasks` redirects to `apps/cluster`
This enables Monster UI to load, reload or redirect to apps that use their own sub-routing system.
Normal routes (app/{appName}) and invalid routes should work as usual.
> [5.1] MSTR-228: Allow app custom routing

- src/apps/appstore/app.js
- src/apps/appstore/i18n/en-US.json
- src/apps/appstore/style/app.scss
- src/apps/appstore/views/app.html
- src/apps/appstore/views/marketClusterLink.html
- src/apps/appstore/views/marketConnectorSettings.html
- src/apps/appstore/views/marketWelcome.html
This adds some notices indicating the app marketplace is in alpha phase.
Also it adds the ability to cancel and disable marketplace connector from Cluster Link step and go back to welcome screen.
* adding alpha ribbon to connector button on left side (normal mode):
* adding alpha ribbon to connector button on left side (hove mode mode):
* notices in marketplace connector pages:
* cancel and disable button at the bottom of cluster link page:
> MSTR-230: Add an alpha tag and notice to marketplace pages

- src/apps/appstore/app.js
- src/apps/appstore/i18n/en-US.json
- src/apps/appstore/style/app.scss
- src/apps/appstore/views/app.html
- src/apps/appstore/views/marketClusterLink.html
- src/apps/appstore/views/marketConnectorSettings.html
- src/apps/appstore/views/marketWelcome.html
This adds some notices indicating the app marketplace is in alpha phase.
Also it adds the ability to cancel and disable marketplace connector from Cluster Link step and go back to welcome screen.
* adding alpha ribbon to connector button on left side (normal mode):
* adding alpha ribbon to connector button on left side (hove mode mode):
* notices in marketplace connector pages:
﻿ ![image](https://user-images.githubusercontent.com/4894215/180617050-e42a2207-48bf-4428-af3a-031e8b516aa0.png)
* cancel and disable button at the bottom of cluster link page:
> [5.1] MSTR-230: Add an alpha tag and notice to marketplace pages

- src/js/lib/monster.routing.js
…more than one hyphen
Current pattern provided to crossroads.addRouter to extract appName from url is trimming values such as `service-plan-assignment` and `integration-google-drive`, due to it stops after first hyphen, so for example `integration-google-drive` becomes `integration-google`.
Apps affected by this issue
- Service Plan Assignment
- Service Plan Override
- One Bill Integration
- Google Drive Connector
> MGDC-3: Pattern used in crossroads is no longer trimming app names with more than one hyphen

- src/js/lib/monster.ui.js
Pass the element that triggers `clipboard` click events to the invoking callback in order to access their custom `dataset` attributes for copying purposes
Show a custom success message if needed but fallback to the previous one if none is provided
> MSPB-295,MSPB-296: Pass the trigger element to the clipboard callback

- src/js/lib/monster.ui.js
Pass the element that triggers clipboard click events to the invoking callback in order to access their custom dataset attributes for copying purposes
Show a custom success message if needed but fallback to the previous one if none is provided
> [5.1] MSPB-295,MSPB-296: Pass the trigger element to the clipboard callback

- src/apps/common/submodules/conferenceViewer/conferenceViewer.js
The issue is that in 5.1 we used to get `data._read_only`
And now in 5.2, the API response is different, now we need to get `metadata` for some values:
> MCON-19: Fix issue with conferences due to changes in the API response

- src/apps/common/submodules/extensionTools/extensionTools.js
- src/apps/common/submodules/extensionTools/views/getNewDialog.html
Revised data processing to use the unaltered `number` variable instead of `parsedNumber`, as `parseInt()` automatically removes any leading zeros, and altered the HTML table column data type from `number` to `text` to counteract HTML's numerical data design which also strips leading zeros, thereby ensuring the preservation of leading zeros in extension numbers
> MSTR-273: Preserve leading zeros in extension numbers

- src/apps/common/submodules/extensionTools/extensionTools.js
- src/apps/common/submodules/extensionTools/views/getNewDialog.html
Revised data processing to use the unaltered `number` variable instead of `parsedNumber`, as `parseInt()` automatically removes any leading zeros, and altered the HTML table column data type from `number` to `text` to counteract HTML's numerical data design which also strips leading zeros, thereby ensuring the preservation of leading zeros in extension numbers
> [5.1] MSTR-273: Preserve leading zeros in extension numbers

- src/apps/common/submodules/extensionTools/extensionTools.js
- src/apps/common/submodules/extensionTools/views/getNewDialog.html
Revised data processing to use the unaltered `number` variable instead of `parsedNumber`, as `parseInt()` automatically removes any leading zeros, and altered the HTML table column data type from `number` to `text` to counteract HTML's numerical data design which also strips leading zeros, thereby ensuring the preservation of leading zeros in extension numbers
> [5.3] MSTR-273: Preserve leading zeros in extension numbers

- src/apps/appstore/app.js
- src/apps/appstore/i18n/en-US.json
- src/apps/appstore/views/marketUnlinkedCluster.html
handling when monsterui marketplace connector returns 401 error from appex-server when we open connector and showing a view to complete the unlinking process and then return to the link cluster view.
> [5.3] MSTR-270: adding new view to show when cluster was unlinked from portal and then return error when entering on monster ui

- src/js/lib/monster.util.js
The `pathToFeatures` snippet has been updated to utilize the newly introduced "metadata" field in Kazoo 5.3, along with an improved mapping of `features`
> [5.3] MSPB-352: Fix e911 Erasure on Account CallerID Selection via SmartPBX

- src/js/lib/monster.util.js
The `pathToFeatures` snippet has been updated to utilize the newly introduced "metadata" field in Kazoo 5.3, along with an improved mapping of `features`
> MSPB-352: Fix e911 Erasure on Account CallerID Selection via SmartPBX

- src/apps/myaccount/submodules/billing/billing.js
- src/apps/myaccount/submodules/creditCard/creditCard.js
- Added `hasVerifiedACH` check to prevent the payment method pop-up after successful ACH setup.
- Ensured the pop-up triggers only when necessary conditions are unmet.
> MSTR-327: Fix Payment Method Pop-up After Successful ACH Setup

- src/apps/myaccount/submodules/billing/billing.js
- src/apps/myaccount/submodules/creditCard/creditCard.js
- Added `hasVerifiedACH` check to prevent the payment method pop-up after successful ACH setup.
- Ensured the pop-up triggers only when necessary conditions are unmet.
> [5.3] MSTR-327: Fix Payment Method Pop-up After Successful ACH Setup

- docs/configuration.md
- src/apps/common/submodules/mediaSelect/mediaSelect.js
- src/apps/core/i18n/de-DE.json
- src/apps/core/i18n/en-GB.json
- src/apps/core/i18n/en-US.json
- src/apps/core/i18n/fr-CA.json
- src/apps/core/i18n/fr-FR.json
- src/apps/core/i18n/nl-NL.json
- src/apps/core/i18n/ru-RU.json
- src/apps/myaccount/submodules/account/views/layout.html
- src/apps/myaccount/submodules/user/views/layout.html
- src/js/lib/monster.js
- Adding `nl-BE` as a supported language in the Account and User settings
- Enabling `whitelabel` support for `tts.voice` changes in SmartPBX
> MSPB-385: Add `nl-BE` language and `tts.voice` `whitelabel` support

- docs/configuration.md
- src/apps/common/submodules/mediaSelect/mediaSelect.js
- src/apps/core/i18n/de-DE.json
- src/apps/core/i18n/en-GB.json
- src/apps/core/i18n/en-US.json
- src/apps/core/i18n/fr-CA.json
- src/apps/core/i18n/fr-FR.json
- src/apps/core/i18n/nl-NL.json
- src/apps/core/i18n/ru-RU.json
- src/apps/myaccount/submodules/account/views/layout.html
- src/apps/myaccount/submodules/user/views/layout.html
- src/js/lib/monster.js
- Adding `nl-BE` as a supported language in the Account and User settings
- Enabling `whitelabel` support for `tts.voice` changes in SmartPBX
> [5.4] MSPB-385: Add `nl-BE` language and `tts.voice` `whitelabel` support
