2600hz/monster-ui

apps/auth/app.js

Needed for https://github.com/2600hz/kazoo/pull/1451

KAZOO-3669: send UI URL for the backend to build the reset-password link

---

docs/kazooSdk.md

Just a minor fix for the example listed for kazooSdk - this is my first time trying to help with anything so let me know if I'm not following proper practice.

minor doc fix

---

js/lib/jquery.kazoosdk.js

not sure that changes anything, but it's more correct ;)

tasks in/output MIME is actually CSV

---

apps/common/submodules/buyNumbers/buyNumbers.js
docs/kazooSdk.md
js/lib/jquery.kazoosdk.js

allows subaccounts to buy reserved numbers in reseller

search numbers with account-id

---

docs/mkdocs/index.md

Checking if the hook on Monster-UI PRs for docs work

OOB: Test PR Update docs

---

src/apps/common/submodules/numbers/numbers.js
src/js/lib/monster.ui.js

- remove manual formatting for MDNs
- update signal strength indicator component to support up to 5 different levels
- add new validation rule to validate hexadecimal strings

UI-2559: Changes related to TOP v2 APIs upgrade

---

src/js/lib/monster.ui.js

I see you replaced lodash with underscorejs _.merge needs to be replaced with _.extend

underscorejs use _.extend instead of _.merge

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/portListing/portListing.js
src/apps/common/submodules/portListing/portListing.scss
src/apps/common/submodules/portListing/views/detail.html
src/apps/common/submodules/portListing/views/timeline-entry.html
src/css/lib/monster.scss

UI-3257: Allow super-duper user to post private comments at port request

---

src/js/lib/monster.apps.js

Update both current and originalAccount after on account update request success, if needed.

UI-3301: Load main number's E911 dialog on top notification click at Smart PBX

---

src/js/lib/jquery.kazoosdk.js

I made a mistake and it was supposed to be ruleId isntead of SkillId

UI-3322: Fix rule_id for Skill_rules APIs

---

src/apps/myaccount/i18n/en-US.json
src/apps/myaccount/submodules/balance/balance.js
src/apps/myaccount/submodules/balance/balance.scss
src/apps/myaccount/submodules/balance/views/addCreditDialog.html

~~Requires #342~~ see https://github.com/2600hz/monster-ui/pull/344/commits/d742c07d45087bfbfbf04ab186ce6814a99a1459

UI-3377:  Improve layout for subscriptions selection feature

---

src/apps/myaccount/submodules/transactions/transactions.js

MSTR-2: Fix transactions total

---

package-lock.json
package.json

Address:
```txt
Low             Regular Expression Denial of Service                          
Package         braces                                                        
Dependency of   browser-sync [dev]                                            
Path            browser-sync > micromatch > braces                            
More info       https://npmjs.com/advisories/786
```

MSTR-6: Bump browser-sync to fix ReDoS vulnerability

---

src/apps/common/submodules/navigationWizard/navigationWizard.scss
src/apps/common/submodules/navigationWizard/views/layout.html

Merge changes needed to improve the look for the navigation wizard common controller

UI-3385: Make some design changes (#359)

---

src/apps/common/submodules/navigationWizard/navigationWizard.scss

MSTR-9: Fix the blue indicator alignment and check-mark size

MSTR-9: Fix the blue indicator alignment and check-mark size (#361)

---

src/apps/common/submodules/navigationWizard/navigationWizard.scss
src/apps/common/submodules/navigationWizard/views/layout.html

support custom actions and title

MSTR-15: Customize navigation wizard

---

src/apps/common/submodules/dragableUploads/dragableUploads.js

Return files without upload them

MSTR-16: New param to return file list without upload them

---

docs/configuration.md
docs/monster-ui/mask().md
src/apps/apploader/app.js
src/apps/common/submodules/appSelector/appSelector.js
src/css/lib/monster.scss

MSTR-66: Add error callback for getAppList

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/navigationWizard/navigationWizard.js
src/apps/common/submodules/navigationWizard/navigationWizard.scss

Optionally validate the current step before moving to another one, and not only when moving forward to the next step. Also, show a confirm dialog before leaving the wizard on cancel.

MSTR-60: Wizard optionally validate on step change

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/navigationWizard/navigationWizard.js
src/apps/common/submodules/navigationWizard/navigationWizard.scss

Optionally validate the current step before moving to another one, and not only when moving forward to the next step. Also, show a confirm dialog before leaving the wizard on cancel.

[4.3] MSTR-60: Wizard optionally validate on step change

---

src/apps/myaccount/submodules/balance/balance.js

4.3 -> https://github.com/2600hz/monster-ui/pull/493

MSTR-106: Query ledgers using UTC based Gregorian timestamps

---

src/apps/common/submodules/navigationWizard/navigationWizard.js

Also, disable footer action buttons while the step is being loaded.

MSTR-56: Load and render wizard step asynchronously

---

src/apps/common/submodules/navigationWizard/navigationWizard.js

Also, disable footer action buttons while the step is being loaded.

[4.3] MSTR-56: Load and render wizard step asynchronously

---

src/apps/common/submodules/navigationWizard/navigationWizard.scss
src/apps/common/submodules/portWizard/partials/_step-carrierSelection.scss
src/apps/common/submodules/portWizard/partials/_step-nameAndNumbers.scss
src/apps/common/submodules/portWizard/portWizard.js
src/apps/common/submodules/portWizard/views/step-carrierSelection-multiple.html

It also includes small code changes to improve readability.

MSTR-122: Tweak port wizard styles to match mockup

---

src/apps/common/submodules/navigationWizard/navigationWizard.js

MSTR-126: Allow to enable/disable wizard buttons

---

src/apps/common/submodules/navigationWizard/navigationWizard.js

MSTR-128: Fix initial completed steps status error

---

src/apps/auth/app.js
src/apps/core/app.js
src/js/lib/monster.socket.js
src/js/lib/monster.util.js

Takes care of the following:
- Only attempt to open WS connection once a user is logged in
- Prevent multiple WS connections to be opened on reconnect

MSTR-129: Enforce only one WS connection to be opened once logged in

---

src/js/lib/monster.routing.js

It was possible to access an app by its route even when a user did not
have the permissions to use it.
Before loading an app, we now check the relevant permissions
(all/admin/user specific) and when an app is not loadable, we revert to
load the last loaded app if possible, or the default app.

[4.3] MSTR-113: Enforce app permissions on route update

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/portWizard/portWizard.js

Verify that all the numbers entered in the first step belong to the selected number type.

MSTR-136: Validate selected number type

---

src/apps/core/style/app.scss

MSTR-154: Fix topbar app icon position when name is empty

---

src/apps/common/submodules/navigationWizard/navigationWizard.js
src/apps/common/submodules/portWizard/portWizard.js
src/apps/common/submodules/portWizard/views/step-ownershipConfirmation-accountInfo.html
src/apps/common/submodules/portWizard/views/step-review.html

Check the requirements and restrictions again if any new number is added to the port request:
* Check that the numbers belong to the same carrier and country
* Verify that there is at least one destination carrier available
* Check required documents and data based on the country
Also, include current and completed step info on save draft, so that the wizard can be opened in the same current step when the draft is loaded for edit.

MSTR-152: Check requirements after number change

---

src/apps/core/style/app.scss

MSTR-156: Fix vertical align for topbar inline text

---

src/css/lib/monster.scss

MSTR-157: Show checkbox/radio grey mark only on hover

---

src/js/lib/jquery.kazoosdk.js

MSTR-159: Add API endpoint to list devices by user

---

src/js/lib/jquery.kazoosdk.js

[4.3] MSTR-159: Add API endpoint to list devices per user

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/navigationWizard/navigationWizard.js
src/apps/common/submodules/portWizard/portWizard.js
src/apps/common/submodules/portWizard/views/step-carrierSelection-multiple.html
src/apps/common/submodules/portWizard/views/step-dateAndNotifications-email.html
src/apps/core/views/svg-container.html

This PR includes multiple small fixes, mostly related to the country requirements for number port, and how they affect the wizard navigation. It also includes some tweaks to the data handling (when and which data to save, timezone handling).
The changes and fixes applied are listed and described briefly in the commits.

MSTR-158: Fix requirement checks & wizard navigation

---

package-lock.json

Remediate vulnerabilities of the following modules:
- `minimist`
- `acorn`
- `kind-of`

[4.3] Remediate vulnerabilities

---

src/apps/common/submodules/chooseModel/chooseModel.js

For Polycom Models, Prefix VVX in front of all VVX model names in Monster UI
The family information is already available on the payload, it just need to be added to the string displayed to avoid confusions.

MPRO-7: For Polycom Models, Prefix VVX in front of all VVX model names in Monster UI

---

src/apps/common/submodules/accountBrowser/accountBrowser.js

MSTR-163: Add new account under selected parent

---

src/apps/apploader/app.js
src/apps/common/submodules/appSelector/appSelector.js

MSTR-172: Specify account for app selector list

---

src/apps/common/submodules/navigationWizard/navigationWizard.js

MSTR-176: Use class to hide wizard footer buttons

---

docs/monster-ui/showPasswordStrength().md
src/apps/common/submodules/navigationWizard/navigationWizard.scss
src/apps/core/views/monster-password-strength-bar.html
src/apps/core/views/monster-password-strength-emoji.html
src/apps/core/views/monster-password-strength-icon.html
src/css/lib/monster.ui.scss
src/js/lib/monster.ui.js

MSTR-178: Add emoji strength indicator

---

src/apps/common/submodules/conferenceViewer/conferenceViewer.js
src/apps/common/submodules/conferenceViewer/views/layout.html

5.0 -> https://github.com/2600hz/monster-ui/pull/794
4.3 -> https://github.com/2600hz/monster-ui/pull/795

MCON-8: Disable participants invite for locked conferences

---

src/apps/auth/app.js

Revert "MSTR-200: Do not make the username lowercase when logging in to monst…"

---

src/apps/auth/app.js

[5.0] Revert "MSTR-200: Do not make the username lowercase when logging in to monst…"

---

src/apps/common/submodules/mediaSelect/mediaSelect.js

5.0 -> https://github.com/2600hz/monster-ui/pull/851

MSTR-211: List TTS as selectable media entities

---

src/apps/appstore/app.js
src/apps/appstore/views/appList.html

master -> https://github.com/2600hz/monster-ui/pull/852

[5.0] MSTR-207: Fix appstore management when masquerading

---

src/apps/core/i18n/en-US.json
src/js/lib/monster.ui.js
src/js/lib/monster.util.js

Supporting PRs:
- https://github.com/2600hz/monster-ui-provisioner/pull/47
- https://github.com/2600hz/monster-ui-accounts/pull/172

[5.0] MACT-89: Enforce lowercased realm validation

---

src/apps/apploader/style/app.scss
src/apps/apploader/views/app.html
src/apps/appstore/style/app.scss

MUDA-7: Fix application label overflow

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/csvUploader/csvUploader.js

Supports:
- https://github.com/2600hz/monster-ui-voip/pull/331
- https://github.com/2600hz/monster-ui-provisioner/pull/49

MSPB-157: Abstract row validation on CSV uploading

---

src/js/lib/monster.ui.js

5.0 -> https://github.com/2600hz/monster-ui/pull/886

MSPB-176: Fix context references access

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/servicePlanItemEditor/servicePlanItemEditor.js
src/apps/common/submodules/servicePlanItemEditor/views/field-plan-details.html

MSTR-218: Expose service plan item `name` prop as editable

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/e911/e911.js
src/apps/core/i18n/en-US.json
src/js/lib/monster.ui.js

MSTR-214: Validate list of space separated e911 email addresses

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/cidNumber/cidNumber.js
src/apps/common/submodules/cidNumber/views/add.html
src/apps/common/submodules/numbers/numbers.js
src/apps/common/submodules/numbers/views/external.html
src/js/lib/monster.ui.js

Revert "PROD-199: Improve UX for cid number addition"

---

src/js/main.js
src/js/templates.js
src/js/vendor/handlebars-v4.7.7.js

Add noEscape option to handlebars for string templates

---

src/apps/common/i18n/en-US.json
src/apps/common/submodules/numberSelector/numberSelector.js
src/apps/common/submodules/numberSelector/views/layout.html

[5.1] MCIM-23: Add existing callerid to numberSelector

---

src/apps/auth/app.js
src/js/lib/monster.js
src/js/lib/monster.ui.js
src/js/lib/monster.util.js

- Generate feature set from config and auth token
- Expose helper to access feature set config

PS-49: Expose helpers to access feature set config

---

src/js/lib/monster.js

Feature set flag for external event/message base navigation routing in SmartPBX

MSPB-315: Expose SmartPBX feature for external event based routing

---

src/apps/common/submodules/buyNumbers/buyNumbers.js

[5.1] MSTR-236: Remove internal IP

---

docs/configuration.md
src/apps/myaccount/app.js
src/js/lib/monster.js

Added new configuration setting/logic for disabling new user walkthrough.

MSPB-319: Added new setting/ability for disabling walkthrough

---

src/apps/auth/app.js

…' stored in auth account data

MSTR-240: Fix typo from 'wnm_allow_additions' stored in auth account data

---

src/js/lib/jquery.kazoosdk.js

Update phone number list API URL to use proper URL encoding method for encoding brackets "[]"

MSPB-325: Fix URL encoding issue for phone number list query

---

src/js/lib/jquery.kazoosdk.js

Update phone number list API URL to use proper URL encoding method for encoding brackets "[]"

[5.2] MSPB-325: Fix URL encoding issue for phone number list query

---

docs/using-postman-as-a-crud.md

Last PR had an erroneous link (sorry!)

OOB: Link postman collection and environment to GitHub

---

docs/using-postman-as-a-crud.md

Last one had erroneous links (sorry!)

[5.1] OOB: Link postman collection and environment to GitHub

---

docs/using-postman-as-a-crud.md

Last PR had erroneous links (sorry!)

[5.2] OOB: Link postman collection and environment to GitHub

---

src/js/lib/monster.js

Key change from entitlements to bluejeans as per kazoo-bluejeans changes
https://github.com/2600hz/kazoo-bluejeans/commit/1e50eb1288b6153cbd1b8dffdee68f97e0e54bf3

PS-49: FeatureSet Token key change

---

src/js/lib/monster.js

Key change from entitlements to bluejeans as per kazoo-bluejeans changes
https://github.com/2600hz/kazoo-bluejeans/commit/1e50eb1288b6153cbd1b8dffdee68f97e0e54bf3

[5.2] PS-49: FeatureSet Token key change

---

src/apps/myaccount/submodules/balance/balance.js

MSTR-263: Do not override the subscription selection when changing the auto recharge

---

docs/configuration.md
src/js/lib/monster.js

Added new configuration setting/logic for configuring month range selection in Invoice Generator

MINV-4: Added new setting/ability for configurable month range selection

---

src/js/lib/jquery.kazoosdk.js

Backport for https://github.com/2600hz/monster-ui/pull/1020

[5.1] MBRA-18: Expose ability to pick protocol to perform DNS check

---

src/js/lib/jquery.kazoosdk.js

[5.3] MUDA-13: add new endpoints to enable chat workspace and list users with chat

---

docs/configuration.md
docs/mkdocs/mkdocs.yml
docs/monster-util/isAuthorizedTopicForCrossSiteMessaging().md
src/apps/core/app.js
src/js/lib/monster.js
src/js/lib/monster.util.js

Logic for cross-site message event binding, publication and authorization check as well as removal of event routing flag (_used in previous implementation_)

[5.3] MSPB-315: Cross-site message based routing

---

src/js/lib/monster.apps.js

UI applications started via Marketplace will set `source_url` in their metadata to make Monster UI fetch their assists files from the that URL.
This tries to fix some issues that preventing requiring app's JS files via external `source_url`.
Marketplace set the source_url to something like this:
`{API_URL}/ui/{NAME_OF_UI_APP}/[...]`
- `API_URL`: the crossbar api url, set my Marketplace Connector to  `monster.config.api.default`
- `NAME_OF_UI_APP`: Marketplace name of UI app (like `monsterui_accounts`)
- `[...]`: the path to fetch the file.
So for example given `http://localhost:8000/v2` being API URL the `source_url` for `monsterui_accounts` is set by Kazoo to:
`monsterui_accounts` metadata looks like this:
```
{
...
"source_url": "http://localhost.8000/ui/monsterui_accounts",
...
}
``` …

MSTR-275: Fix loading module/submodule files from external source_url

---

src/js/lib/monster.apps.js

UI applications started via Marketplace will set `source_url` in their metadata to make Monster UI fetch their assists files from the that URL.
This tries to fix some issues that preventing requiring app's JS files via external `source_url`.
Marketplace set the source_url to something like this:
`{API_URL}/ui/{NAME_OF_UI_APP}/[...]`
- `API_URL`: the crossbar api url, set my Marketplace Connector to  `monster.config.api.default`
- `NAME_OF_UI_APP`: Marketplace name of UI app (like `monsterui_accounts`)
- `[...]`: the path to fetch the file.
So for example given `http://localhost:8000/v2` being API URL the `source_url` for `monsterui_accounts` is set by Kazoo to:
`monsterui_accounts` metadata looks like this:
```
{
...
"source_url": "http://localhost.8000/ui/monsterui_accounts",
...
}
``` …

[5.3] MSTR-275: fix loading module/submodule files from external source_url

---

package.json

MSTR-282 Changed monsterui version for testing purposes

MSTR-282 Changed monsterui version

---

package.json

MSTR-282: Reverted changes back to 4.3.0

MSTR-282: Reverted changes back to 4.3.0

---

README.md

MSTR-285 Added whitespace

---

src/apps/myaccount/app.js
src/apps/myaccount/i18n/de-DE.json
src/apps/myaccount/i18n/en-US.json
src/apps/myaccount/i18n/fr-FR.json
src/apps/myaccount/i18n/nl-NL.json
src/apps/myaccount/i18n/ru-RU.json
src/apps/myaccount/submodules/ach/ach.js
src/apps/myaccount/submodules/ach/views/ach-section-verification.html
src/apps/myaccount/submodules/billing/billing.js
src/apps/myaccount/submodules/billing/views/layout.html
src/apps/myaccount/submodules/creditCard/creditCard.js

[5.3] MSTR-301: Fix billing and credit card validation conditions

---

src/apps/common/i18n/de-DE.json
src/apps/common/i18n/en-US.json
src/apps/common/i18n/fr-FR.json
src/apps/common/i18n/nl-NL.json
src/apps/common/i18n/ru-RU.json
src/apps/common/submodules/e911/e911.js
src/apps/common/submodules/e911/e911.scss
src/apps/common/submodules/e911/views/dialog.html

* MSTR-300: Add support to intrado when adding a e911 to a number
* Add dropdown to country field
* Add street number to address

[5.4] MSTR-300: Add support to intrado when adding a e911 to a number (#1177)

---

src/apps/myaccount/submodules/balance/balance.js

https://github.com/2600hz/monster-ui/pull/1259

MSPB-379: set  timezone on balance filters
